### ISSUE TITLE
Erroneous deletion of answers in case of duplicate questions

### ISSUE THREAD

**Issue by howlger** [blackgreen100/SO-hammer-with-list#9]
If a question has been closed as a duplicate, then it should be allowed to copy a correct answer from the closed question to the original opened question. Deleting a visible correct answer instead of the hidden duplicated answer must be avoided not to harm users.

The deleting of correct answers based on the insinuation that someone is acting in bad faith violates also the [Code of Conduct](https://stackoverflow.com/conduct).

**Comment by blackgreen100** [comment]
@howlger Please can you explain how this issue relates to the code in this repository? This script doesn't delete answers, it only closes questions as duplicate.
